num_um = int(input("Digite o 1º numero: "))
num_dois = int(input("Digite o 2º numero: "))

print("")
print("A soma entre os numero é: ", num_um + num_dois)
print("")
print("A subtracao entre os numero é: ", num_um - num_dois)
print("")
print("A multiplicacao entre os numero é: ", num_um * num_dois)
print("")
print("A divicao entre os numero é: ", num_um / num_dois)
